TOKEN = ""
DATABASE_USER = ""
DATABASE_PASS = ""
VERBOSE: int = 0
PROCESSING_SERVER_ADDRESS = "tcp://localhost:5555"
PROCESSING_SERVER_TIMEOUT_MILLISECONDS = 60000
DATABASE_BACKUP_LOCATION = "/workspace/albedo-bot/"
