"""Added HeroPortrait table for tracking images in the hero database

Revision ID: a7fd51241282
Revises: a644106254d1
Create Date: 2022-08-22 08:03:21.544740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fd51241282'
down_revision = 'a644106254d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_portraits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_index', sa.Integer(), nullable=False),
    sa.Column('required', sa.Integer(), nullable=False),
    sa.Column('image_directory', sa.String(), nullable=True),
    sa.Column('image_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('id', 'image_index', 'required')
    )
    op.drop_column('heroes', 'hero_portrait')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('hero_portrait', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('hero_portraits')
    # ### end Alembic commands ###
